//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pluto.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pluto.Wpf.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string AttendanceDialog_Back {
            get {
                return ResourceManager.GetString("AttendanceDialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AttendanceDialog_Button_Add {
            get {
                return ResourceManager.GetString("AttendanceDialog_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AttendanceDialog_Button_Save {
            get {
                return ResourceManager.GetString("AttendanceDialog_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string AttendanceDialog_Date {
            get {
                return ResourceManager.GetString("AttendanceDialog_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time:.
        /// </summary>
        public static string AttendanceDialog_EndTime {
            get {
                return ResourceManager.GetString("AttendanceDialog_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AttendanceDialog_Name {
            get {
                return ResourceManager.GetString("AttendanceDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attendance.
        /// </summary>
        public static string AttendanceDialog_Question {
            get {
                return ResourceManager.GetString("AttendanceDialog_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        public static string AttendanceDialog_StartTime {
            get {
                return ResourceManager.GetString("AttendanceDialog_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm.
        /// </summary>
        public static string AttendanceDialog_TimeFormat {
            get {
                return ResourceManager.GetString("AttendanceDialog_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attendance.
        /// </summary>
        public static string AttendanceDialog_Title_AddAttendance {
            get {
                return ResourceManager.GetString("AttendanceDialog_Title_AddAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attendance.
        /// </summary>
        public static string AttendanceDialog_Title_Delete {
            get {
                return ResourceManager.GetString("AttendanceDialog_Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit attendance.
        /// </summary>
        public static string AttendanceDialog_Title_EditAttendance {
            get {
                return ResourceManager.GetString("AttendanceDialog_Title_EditAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        public static string Button_Curriculum {
            get {
                return ResourceManager.GetString("Button_Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        public static string Button_Language {
            get {
                return ResourceManager.GetString("Button_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Button_Subjects {
            get {
                return ResourceManager.GetString("Button_Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Button_Terms {
            get {
                return ResourceManager.GetString("Button_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Checkbox_Completed {
            get {
                return ResourceManager.GetString("Checkbox_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subject.
        /// </summary>
        public static string CurriculumPage_Button_DeleteSubject {
            get {
                return ResourceManager.GetString("CurriculumPage_Button_DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subject.
        /// </summary>
        public static string CurriculumPage_Button_EditSubject {
            get {
                return ResourceManager.GetString("CurriculumPage_Button_EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subject.
        /// </summary>
        public static string CurriculumPage_Button_NewSubject {
            get {
                return ResourceManager.GetString("CurriculumPage_Button_NewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register subject.
        /// </summary>
        public static string CurriculumPage_Button_RegisterSubject {
            get {
                return ResourceManager.GetString("CurriculumPage_Button_RegisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister subject.
        /// </summary>
        public static string CurriculumPage_Button_UnregisterSubject {
            get {
                return ResourceManager.GetString("CurriculumPage_Button_UnregisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string CurriculumPage_ListviewHeader_Completed {
            get {
                return ResourceManager.GetString("CurriculumPage_ListviewHeader_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string CurriculumPage_ListviewHeader_Credit {
            get {
                return ResourceManager.GetString("CurriculumPage_ListviewHeader_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CurriculumPage_ListviewHeader_Name {
            get {
                return ResourceManager.GetString("CurriculumPage_ListviewHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string CurriculumPage_ListviewHeader_Registered {
            get {
                return ResourceManager.GetString("CurriculumPage_ListviewHeader_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        public static string CurriculumPage_Title {
            get {
                return ResourceManager.GetString("CurriculumPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Label_Loading {
            get {
                return ResourceManager.GetString("Label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term.
        /// </summary>
        public static string Label_Term {
            get {
                return ResourceManager.GetString("Label_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Label_Welcome {
            get {
                return ResourceManager.GetString("Label_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string RegisteredSubjectDialog_Button_Back {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisteredSubjectDialog_Button_Register {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject is completed.
        /// </summary>
        public static string RegisteredSubjectDialog_Message_Completed {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Message_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject is already registered.
        /// </summary>
        public static string RegisteredSubjectDialog_Message_Registered {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Message_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject is unregistered or completed.
        /// </summary>
        public static string RegisteredSubjectDialog_Message_Unregister {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Message_Unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to unregister this subject.
        /// </summary>
        public static string RegisteredSubjectDialog_Question_Unregister {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Question_Unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register subject.
        /// </summary>
        public static string RegisteredSubjectDialog_Title_Register {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister subject.
        /// </summary>
        public static string RegisteredSubjectDialog_Title_Unregister {
            get {
                return ResourceManager.GetString("RegisteredSubjectDialog_Title_Unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select term:.
        /// </summary>
        public static string RegisterSubjectDialog_SelectTerm {
            get {
                return ResourceManager.GetString("RegisterSubjectDialog_SelectTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SubjectDialog_Back {
            get {
                return ResourceManager.GetString("SubjectDialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string SubjectDialog_Button_Create {
            get {
                return ResourceManager.GetString("SubjectDialog_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SubjectDialog_Button_Save {
            get {
                return ResourceManager.GetString("SubjectDialog_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit:.
        /// </summary>
        public static string SubjectDialog_Credit {
            get {
                return ResourceManager.GetString("SubjectDialog_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string SubjectDialog_Message_Question {
            get {
                return ResourceManager.GetString("SubjectDialog_Message_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject cannot be deleted!.
        /// </summary>
        public static string SubjectDialog_Message_Warning {
            get {
                return ResourceManager.GetString("SubjectDialog_Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string SubjectDialog_Name {
            get {
                return ResourceManager.GetString("SubjectDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubjectDialog_Question_SubjectWord {
            get {
                return ResourceManager.GetString("SubjectDialog_Question_SubjectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subject.
        /// </summary>
        public static string SubjectDialog_Title_Create {
            get {
                return ResourceManager.GetString("SubjectDialog_Title_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subject.
        /// </summary>
        public static string SubjectDialog_Title_Delete {
            get {
                return ResourceManager.GetString("SubjectDialog_Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subject.
        /// </summary>
        public static string SubjectDialog_Title_Edit {
            get {
                return ResourceManager.GetString("SubjectDialog_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        public static string SubjectsPage_Attendances {
            get {
                return ResourceManager.GetString("SubjectsPage_Attendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attendance.
        /// </summary>
        public static string SubjectsPage_Button_AddAttendance {
            get {
                return ResourceManager.GetString("SubjectsPage_Button_AddAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attendance.
        /// </summary>
        public static string SubjectsPage_Button_DeleteAttendance {
            get {
                return ResourceManager.GetString("SubjectsPage_Button_DeleteAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit attendance.
        /// </summary>
        public static string SubjectsPage_Button_EditAttendance {
            get {
                return ResourceManager.GetString("SubjectsPage_Button_EditAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TermDialog_Back {
            get {
                return ResourceManager.GetString("TermDialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TermDialog_Button_Create {
            get {
                return ResourceManager.GetString("TermDialog_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TermDialog_Button_Save {
            get {
                return ResourceManager.GetString("TermDialog_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string TermDialog_Checkbox_Active {
            get {
                return ResourceManager.GetString("TermDialog_Checkbox_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        public static string TermDialog_EndDate {
            get {
                return ResourceManager.GetString("TermDialog_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This term cannot be deleted! Only not closed and empty term can be deleted.
        /// </summary>
        public static string TermDIalog_Meassage_DeleteLastTerm {
            get {
                return ResourceManager.GetString("TermDIalog_Meassage_DeleteLastTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This term cannot be closed.
        /// </summary>
        public static string TermDialog_Message_CloseTerm {
            get {
                return ResourceManager.GetString("TermDialog_Message_CloseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this term.
        /// </summary>
        public static string TermDialog_Question_CloseTerm {
            get {
                return ResourceManager.GetString("TermDialog_Question_CloseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the last term.
        /// </summary>
        public static string TermDialog_Question_DeleteLastTerm {
            get {
                return ResourceManager.GetString("TermDialog_Question_DeleteLastTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string TermDialog_StartDate {
            get {
                return ResourceManager.GetString("TermDialog_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close term.
        /// </summary>
        public static string TermDialog_Title_CloseTerm {
            get {
                return ResourceManager.GetString("TermDialog_Title_CloseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create term.
        /// </summary>
        public static string TermDialog_Title_CreateTerm {
            get {
                return ResourceManager.GetString("TermDialog_Title_CreateTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete last term.
        /// </summary>
        public static string TermDialog_Title_DeleteLastTerm {
            get {
                return ResourceManager.GetString("TermDialog_Title_DeleteLastTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit term.
        /// </summary>
        public static string TermDialog_Title_EditTerm {
            get {
                return ResourceManager.GetString("TermDialog_Title_EditTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close term.
        /// </summary>
        public static string TermsPage_Button_CloseTerm {
            get {
                return ResourceManager.GetString("TermsPage_Button_CloseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete last term.
        /// </summary>
        public static string TermsPage_Button_DeleteLastTerm {
            get {
                return ResourceManager.GetString("TermsPage_Button_DeleteLastTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit term.
        /// </summary>
        public static string TermsPage_Button_EditTerm {
            get {
                return ResourceManager.GetString("TermsPage_Button_EditTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New term.
        /// </summary>
        public static string TermsPage_Button_NewTerm {
            get {
                return ResourceManager.GetString("TermsPage_Button_NewTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string TermsPage_Checkbox_Active {
            get {
                return ResourceManager.GetString("TermsPage_Checkbox_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string TermsPage_Checkbox_Closed {
            get {
                return ResourceManager.GetString("TermsPage_Checkbox_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string TermsPage_Credits {
            get {
                return ResourceManager.GetString("TermsPage_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered credits:.
        /// </summary>
        public static string TermsPage_RegisteredCredits {
            get {
                return ResourceManager.GetString("TermsPage_RegisteredCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TermsPage_Title {
            get {
                return ResourceManager.GetString("TermsPage_Title", resourceCulture);
            }
        }
    }
}
